/*
 * DO NOT EDIT.
 *
 * Generated by the protocol buffer compiler.
 * Source: google/assistant/embedded/v1alpha1/embedded_assistant.proto
 *
 */

/*
 * Copyright 2017, gRPC Authors All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import Foundation
import Dispatch
import gRPC
import SwiftProtobuf

/// Type for errors thrown from generated server code.
internal enum Google_Assistant_Embedded_V1Alpha1_EmbeddedAssistantServerError : Error {
  case endOfStream
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Google_Assistant_Embedded_V1Alpha1_EmbeddedAssistantProvider {
  func converse(session : Google_Assistant_Embedded_V1Alpha1_EmbeddedAssistantConverseSession) throws
}

/// Common properties available in each service session.
internal class Google_Assistant_Embedded_V1Alpha1_EmbeddedAssistantSession {
  fileprivate var handler : gRPC.Handler
  internal var requestMetadata : Metadata { return handler.requestMetadata }

  internal var statusCode : Int = 0
  internal var statusMessage : String = "OK"
  internal var initialMetadata : Metadata = Metadata()
  internal var trailingMetadata : Metadata = Metadata()

  fileprivate init(handler:gRPC.Handler) {
    self.handler = handler
  }
}

// Converse (Bidirectional Streaming)
internal class Google_Assistant_Embedded_V1Alpha1_EmbeddedAssistantConverseSession : Google_Assistant_Embedded_V1Alpha1_EmbeddedAssistantSession {
  private var provider : Google_Assistant_Embedded_V1Alpha1_EmbeddedAssistantProvider

  /// Create a session.
  fileprivate init(handler:gRPC.Handler, provider: Google_Assistant_Embedded_V1Alpha1_EmbeddedAssistantProvider) {
    self.provider = provider
    super.init(handler:handler)
  }

  /// Receive a message. Blocks until a message is received or the client closes the connection.
  internal func receive() throws -> Google_Assistant_Embedded_V1alpha1_ConverseRequest {
    let sem = DispatchSemaphore(value: 0)
    var requestMessage : Google_Assistant_Embedded_V1alpha1_ConverseRequest?
    try self.handler.receiveMessage() {(requestData) in
      if let requestData = requestData {
        do {
          requestMessage = try Google_Assistant_Embedded_V1alpha1_ConverseRequest(serializedData:requestData)
        } catch (let error) {
          print("error \(error)")
        }
      }
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let requestMessage = requestMessage {
      return requestMessage
    } else {
      throw Google_Assistant_Embedded_V1Alpha1_EmbeddedAssistantServerError.endOfStream
    }
  }

  /// Send a message. Nonblocking.
  internal func send(_ response: Google_Assistant_Embedded_V1alpha1_ConverseResponse, completion: @escaping ()->()) throws {
    try handler.sendResponse(message:response.serializedData()) {completion()}
  }

  /// Close a connection. Blocks until the connection is closed.
  internal func close() throws {
    let sem = DispatchSemaphore(value: 0)
    try self.handler.sendStatus(statusCode:self.statusCode,
                                statusMessage:self.statusMessage,
                                trailingMetadata:self.trailingMetadata) {
                                  sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
  }

  /// Run the session. Internal.
  fileprivate func run(queue:DispatchQueue) throws {
    try self.handler.sendMetadata(initialMetadata:initialMetadata) {
      queue.async {
        do {
          try self.provider.converse(session:self)
        } catch (let error) {
          print("error \(error)")
        }
      }
    }
  }
}


/// Main server for generated service
internal class Google_Assistant_Embedded_V1Alpha1_EmbeddedAssistantServer {
  private var address: String
  private var server: gRPC.Server
  private var provider: Google_Assistant_Embedded_V1Alpha1_EmbeddedAssistantProvider?

  /// Create a server that accepts insecure connections.
  internal init(address:String,
              provider:Google_Assistant_Embedded_V1Alpha1_EmbeddedAssistantProvider) {
    gRPC.initialize()
    self.address = address
    self.provider = provider
    self.server = gRPC.Server(address:address)
  }

  /// Create a server that accepts secure connections.
  internal init?(address:String,
               certificateURL:URL,
               keyURL:URL,
               provider:Google_Assistant_Embedded_V1Alpha1_EmbeddedAssistantProvider) {
    gRPC.initialize()
    self.address = address
    self.provider = provider
    guard
      let certificate = try? String(contentsOf: certificateURL, encoding: .utf8),
      let key = try? String(contentsOf: keyURL, encoding: .utf8)
      else {
        return nil
    }
    self.server = gRPC.Server(address:address, key:key, certs:certificate)
  }

  /// Start the server.
  internal func start(queue:DispatchQueue = DispatchQueue.global()) {
    guard let provider = self.provider else {
      fatalError() // the server requires a provider
    }
    server.run {(handler) in
      print("Server received request to " + handler.host
        + " calling " + handler.method
        + " from " + handler.caller
        + " with " + String(describing:handler.requestMetadata) )

      do {
        switch handler.method {
        case "/google.assistant.embedded.v1alpha1.EmbeddedAssistant/Converse":
          try Google_Assistant_Embedded_V1Alpha1_EmbeddedAssistantConverseSession(handler:handler, provider:provider).run(queue:queue)
        default:
          break // handle unknown requests
        }
      } catch (let error) {
        print("Server error: \(error)")
      }
    }
  }
}
