language: objective-c
osx_image: xcode9.1
xcode_project: MacAssistant.xcodeproj

notifications:
  email: false

before_install:
- sudo gem install xcpretty

install:
  - ./install_swiftlint.sh

script:
- cd grpc-swift && make
- swiftlint
- cd - && xcodebuild -workspace MacAssistant.xcworkspace -scheme MacAssistant -configuration Debug | xcpretty
