language: objective-c
osx_image: xcode9.1
xcode_project: MacAssistant.xcodeproj

notifications:
  email: false

before_install:
- sudo gem install xcpretty
- sudo gem install cocoapods
- pod install
- pod update

script:
- cd grpc-swift && make
- cd - && xcodebuild -workspace MacAssistant.xcworkspace -scheme MacAssistant -configuration Debug | xcpretty
